# Generated by Django 4.0.2 on 2022-02-21 21:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0004_softskills_remove_skills_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('positon', models.CharField(max_length=100)),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
