# Generated by Django 4.0.2 on 2022-02-22 18:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0007_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
