# Generated by Django 4.0.2 on 2022-05-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0008_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='github_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='website_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
